from enum import StrEnum


class Stage(StrEnum):
    START = "START"
    AWAIT_ACCOUNT_ID = "AWAIT_ACCOUNT_ID"
    LOOKUP_ACCOUNT = "LOOKUP_ACCOUNT"
    AWAIT_FULL_NAME = "AWAIT_FULL_NAME"
    AWAIT_SECONDARY_FACTOR = "AWAIT_SECONDARY_FACTOR"
    VERIFIED_SHOW_BALANCE = "VERIFIED_SHOW_BALANCE"
    AWAIT_PAYMENT_AMOUNT = "AWAIT_PAYMENT_AMOUNT"
    AWAIT_CARD_DETAILS = "AWAIT_CARD_DETAILS"
    PROCESS_PAYMENT = "PROCESS_PAYMENT"
    SUCCESS_CLOSE = "SUCCESS_CLOSE"
    CANCELLED_CLOSE = "CANCELLED_CLOSE"
    ZERO_BALANCE_CLOSE = "ZERO_BALANCE_CLOSE"
    ACCOUNT_LOOKUP_FAILED_CLOSE = "ACCOUNT_LOOKUP_FAILED_CLOSE"
    VERIFICATION_FAILED_CLOSE = "VERIFICATION_FAILED_CLOSE"
    PAYMENT_FAILED_CLOSE = "PAYMENT_FAILED_CLOSE"
    API_UNAVAILABLE_CLOSE = "API_UNAVAILABLE_CLOSE"


TERMINAL_STAGES = {
    Stage.SUCCESS_CLOSE,
    Stage.CANCELLED_CLOSE,
    Stage.ZERO_BALANCE_CLOSE,
    Stage.ACCOUNT_LOOKUP_FAILED_CLOSE,
    Stage.VERIFICATION_FAILED_CLOSE,
    Stage.PAYMENT_FAILED_CLOSE,
    Stage.API_UNAVAILABLE_CLOSE,
}
